// cocktailsData.js
const cocktails = [
   {
                id: 1,
                name: "Gin Tonic (琴通寧)",
                base: "Gin",
                abvLevel: "low",
                abvDisplay: "10%",
                taste: "清爽/氣泡",
                ingredients: "琴酒, 通寧水, 檸檬角",
                story: "如果寂寞有解藥，那一定是琴通寧氣泡破裂的聲音。它不復雜，就像午後的一場陣雨，來得快，去得也快，只留下清爽的涼意。",
                img: "https://i.ibb.co/TDBQ1DzX/images.jpg",
                method: "直調 (Build)",
                glass: "高球杯 (Highball)",
                steps: ["杯中填滿大冰塊", "倒入琴酒與通寧水", "輕攪一次加入檸檬角"]
            },
            {
                id: 2,
                name: "Negroni (內格羅尼)",
                base: "Gin",
                abvLevel: "med",
                abvDisplay: "24%",
                taste: "苦甜/大人味",
                ingredients: "琴酒, 金巴利 (Campari), 甜香艾酒",
                story: "這是一杯屬於大人的酒。入口時的苦澀，像是吞下了一整天的無奈；但隨後回甘的甜味，又彷彿在告訴你：撐過去，一切都會好起來的。",
                img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDKxS8gFlOAyZBhMbSr8bG_eYF7MVzo6NIRQ&s",
                method: "攪拌 (Stir)",
                glass: "經典杯 (Old Fashioned)",
                steps: ["在調酒杯中攪拌冷卻", "濾掉冰塊倒入新冰杯", "噴灑橙皮油增加香氣"]
            },
            {
                id: 3,
                name: "Mojito (莫希托)",
                base: "Rum",
                abvLevel: "med",
                abvDisplay: "12%",
                taste: "清爽/氣泡",
                ingredients: "蘭姆酒, 薄荷葉, 砂糖, 蘇打水, 檸檬",
                story: "海明威的最愛。將薄荷葉搗碎的過程，就像是把煩惱一點一點地碾碎。喝下一口，彷彿置身於哈瓦那的海岸，海風吹散了所有的燥熱。",
                img: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80",
                method: "直調/搗壓 (Muddle)",
                glass: "高球杯 (Highball)",
                steps: ["杯中搗碎薄荷葉與糖", "加入碎冰與蘭姆酒", "倒入蘇打水輕輕攪拌"]
            },
            {
                id: 4,
                name: "Old Fashioned (老派)",
                base: "Whiskey",
                abvLevel: "high",
                abvDisplay: "32%",
                taste: "辛辣/不甜",
                ingredients: "波本威士忌, 方糖, 苦精, 橙皮",
                story: "正如其名，老派。它不屑於花俏的裝飾，只用時間與冰塊的融化來對話。適合一個人在深夜，坐在皮沙發上，思考那些沒有答案的問題。",
                img: "https://image-cdn-flare.qdm.cloud/q69c866e2b26c9/image/data/31.%E7%B6%93%E5%85%B8%E8%AA%BF%E9%85%92/590c825b0fb841996dd7c27a7ad7fd60.jpg",
                method: "攪拌 (Stir)",
                glass: "經典杯 (Old Fashioned)",
                steps: ["方糖浸泡苦精後搗碎", "加入威士忌與大冰塊", "持續攪拌至冰鎮融水"]
            },
            {
                id: 5,
                name: "Long Island Iced Tea (長島冰茶)",
                base: ["Vodka", "Gin", "Rum", "Tequila"],
                abvLevel: "high",
                abvDisplay: "30%+",
                taste: "酸甜/果香",
                ingredients: "伏特加, 琴酒, 蘭姆酒, 龍舌蘭, 橙酒, 可樂",
                story: "披著茶色外衣的失身酒。它甜美得讓你忘記危險，直到酒精重擊你的腦門。這不是為了品味，這是為了遺忘。今晚，我不打算清醒著回家。",
                img: "https://i.ibb.co/Q3h8fgyF/Gemini-Generated-Image-o6ea1co6ea1co6ea.png",
                method: "搖盪 (Shake)",
                glass: "高球杯 (Highball)",
                steps: ["除可樂外材料倒入雪克杯", "加冰搖盪後倒入裝冰杯中", "最後補滿可樂"]
            },
            {
                id: 6,
                name: "Cosmopolitan (柯夢波丹)",
                base: "Vodka",
                abvLevel: "med",
                abvDisplay: "22%",
                taste: "酸甜/果香",
                ingredients: "伏特加, 橙酒, 蔓越莓汁, 檸檬汁",
                story: "都市傳說中的粉紅佳人。它優雅、時尚，卻也帶著一絲距離感。像是在霓虹燈下的短暫邂逅，美麗，但你知道那不會長久。",
                img: "https://www.thebottleclub.com/cdn/shop/articles/TBC_recipe_image_9-490216.jpg?v=1707230667",
                method: "搖盪 (Shake)",
                glass: "馬丁尼杯 (Martini)",
                steps: ["所有材料加入冰塊搖盪", "濾冰倒入冰凍過的杯中", "噴附橙皮油"]
            },
            {
                id: 7,
                name: "Margarita (瑪格麗特)",
                base: "Tequila",
                abvLevel: "high",
                abvDisplay: "26%",
                taste: "酸甜/果香",
                ingredients: "龍舌蘭, 橙酒, 檸檬汁, 鹽口杯",
                story: "那是為了紀念逝去的戀人而調製的酒。杯口的鹽圈是淚水的味道。每一口都是對回憶的致敬，酸楚中帶著鹹，最後才是酒精的撫慰。",
                img: "https://image-cdn-flare.qdm.cloud/q69c866e2b26c9/image/data/31.%E7%B6%93%E5%85%B8%E8%AA%BF%E9%85%92/1162548884f22223b23fabb168e7b88c.jpg",
                method: "搖盪 (Shake)",
                glass: "淺碟香檳杯 (Coupe)",
                steps: ["用檸檬塗抹杯緣沾鹽圈", "材料加冰搖盪均勻", "濾冰倒入鹽口杯"]
            },
            {
                id: 8,
                name: "Martini (馬丁尼)",
                base: "Gin",
                abvLevel: "high",
                abvDisplay: "35%",
                taste: "辛辣/不甜",
                ingredients: "琴酒, 不甜香艾酒, 橄欖",
                story: "雞尾酒之王。它銳利得像一把手術刀，精準地切開你的偽裝。只有足夠堅強的人，才能直視這杯透明液體後的自己。",
                img: "https://mixology.com.tw/images/recipe/pic/G001.jpg",
                method: "攪拌 (Stir)",
                glass: "馬丁尼杯 (Martini)",
                steps: ["琴酒與香艾酒加冰攪拌", "濾冰倒入冰凍酒杯", "放入橄欖裝飾"]
            },
            {
                id: 9,
                name: "Sidecar (側車)",
                base: "Brandy",
                abvLevel: "high",
                abvDisplay: "28%",
                taste: "酸甜/果香",
                ingredients: "白蘭地, 橙酒, 檸檬汁",
                story: "據說源自一次大戰的機車軍官。這是一杯關於出發與抵達的酒。平衡的酸甜，像是人生旅途中的起伏，喝完它，繼續上路。",
                img: "https://images.vocus.cc/e2f7c81c-1e37-419b-bc0a-283ae9711f40.jpg",
                method: "搖盪 (Shake)",
                glass: "淺碟香檳杯 (Coupe)",
                steps: ["可選擇製作糖口杯緣", "材料加冰搖盪至冷卻", "濾冰倒入杯中"]
            },
            {
                id: 10,
                name: "Daiquiri (戴吉利)",
                base: "Rum",
                abvLevel: "med",
                abvDisplay: "20%",
                taste: "酸甜/果香",
                ingredients: "蘭姆酒, 檸檬汁, 糖漿",
                story: "最簡單的三元素，卻考驗著調酒師的靈魂。它告訴我們，生活不需要太多的裝飾，只要比例對了，簡單也可以很深刻。",
                img: "https://www.thebottleclub.com/cdn/shop/articles/TBC_recipe_image_11-436716.jpg?v=1707230647",
                method: "搖盪 (Shake)",
                glass: "淺碟香檳杯 (Coupe)",
                steps: ["蘭姆酒與酸甜加入雪克杯", "加滿冰塊用力搖盪", "雙重過濾倒入冰杯"]
            },
            {
                id: 11,
                name: "Manhattan (曼哈頓)",
                base: "Whiskey",
                abvLevel: "high",
                abvDisplay: "32%",
                taste: "苦甜/大人味",
                ingredients: "黑麥威士忌, 甜香艾酒, 苦精",
                story: "「雞尾酒之后」。如果不喜歡太甜的庸俗，也不想喝太淡的無聊，那就點它。優雅的紅寶石色澤下，藏著都市夜晚的苦澀與回甘。",
                img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh_MVgRwW8e40l5EsgBeyfVpVYviGMoZB2cw&s",
                method: "攪拌 (Stir)",
                glass: "淺碟香檳杯 (Coupe)",
                steps: ["威士忌與香艾酒加冰攪拌", "攪拌約30秒至冷卻", "濾冰倒入杯中"]
            },
            {
                id: 12,
                name: "Blue Lagoon (藍色珊瑚礁)",
                base: "Vodka",
                abvLevel: "med",
                abvDisplay: "20%",
                taste: "酸甜/果香",
                ingredients: "伏特加, 藍柑橘酒, 檸檬汁, 雪碧",
                story: "把馬爾地夫的海水裝進杯子裡。視覺上的絕對清涼，口感上的甜蜜氣泡。這不是在喝酒，這是給靈魂放的一個短假。",
                img: "https://i0.wp.com/vintageamericancocktails.com/wp-content/uploads/2022/04/blue_lagoon.jpg?resize=500%2C500&ssl=1",
                method: "搖盪 (Shake)",
                glass: "颶風杯 (Hurricane)",
                steps: ["基酒與檸檬汁加冰搖盪", "濾入裝滿冰塊的杯中", "補滿雪碧輕輕攪拌"]
            },
            {
                id: 13,
                name: "Mai Tai (麥泰)",
                base: "Rum",
                abvLevel: "high",
                abvDisplay: "27%",
                taste: "酸甜/果香",
                ingredients: "白蘭姆酒, 黑蘭姆酒, 橙酒, 杏仁糖漿, 檸檬汁",
                story: "大溪地語中的「最棒」。別被它熱帶水果的裝飾騙了，這是一杯酒精濃度不容小覷的重擊。喝下它，就像在熱帶島嶼的營火旁狂歡。",
                img: "https://i0.wp.com/cocktail4party.com/wp-content/uploads/2022/03/mai-tai.jpg-e1648383034104.webp?resize=535%2C399&ssl=1",
                method: "搖盪 (Shake)",
                glass: "傳統杯 (Rocks)",
                steps: ["所有材料加冰用力搖盪", "連同冰塊倒入杯中", "使用薄荷葉裝飾"]
            },
            {
                id: 14,
                name: "Screwdriver (螺絲起子)",
                base: "Vodka",
                abvLevel: "med",
                abvDisplay: "12%",
                taste: "酸甜/果香",
                ingredients: "伏特加, 新鮮柳橙汁",
                story: "據說源自油田工人的隨手特調。簡單到不需要酒譜，卻經典到無人不知。就像生活中的小確幸，不需要太複雜，有甜味就夠了。",
                img: "https://i0.wp.com/cocktail4party.com/wp-content/uploads/2021/09/screwdrivercocktail1-e1632418894663.jpg?fit=1200%2C800&ssl=1",
                method: "直調 (Build)",
                glass: "高球杯 (Highball)",
                steps: ["杯中裝滿冰塊", "倒入伏特加", "補滿柳橙汁稍微攪拌"]
            },
            {
                id: 15,
                name: "Tequila Sunrise (龍舌蘭日出)",
                base: "Tequila",
                abvLevel: "med",
                abvDisplay: "18%",
                taste: "酸甜/果香",
                ingredients: "龍舌蘭, 柳橙汁, 紅石榴糖漿",
                story: "杯中的漸層，是破曉時分的顏色。滾石樂團的最愛，充滿著70年代的搖滾與頹廢。喝的不是酒，是從黑夜走向黎明的過程。",
                img: "https://www.allrecipes.com/thmb/zL0-Fqh_E_Z9vuMMhiV8hbNumTc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/222510-Tequila-Sunrise-Cocktail-ddmfs-4x3-0872-7ddefb6ec8ed40d0930e5b92f178e2cf.jpg",
                method: "直調 (Build)",
                glass: "高球杯 (Highball)",
                steps: ["龍舌蘭與柳橙汁加冰攪拌", "將紅石榴糖漿緩緩沈底", "不要攪拌保留漸層"]
            },
            {
                id: 16,
                name: "Whiskey Highball (威士忌蘇打)",
                base: "Whiskey",
                abvLevel: "low",
                abvDisplay: "7%",
                taste: "清爽/氣泡",
                ingredients: "威士忌, 強氣泡水, 檸檬角",
                story: "下班後的第一選擇。氣泡炸裂的瞬間，帶走了整天的疲憊。不需要細細品嚐，大口喝下，讓冰涼的液體衝刷掉所有的壓力。",
                img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6sbApxmYkbN1wCRu2_UxGlk7yj3Ra-PzwtQ&s",
                method: "直調 (Build)",
                glass: "高球杯 (Highball)",
                steps: ["冰塊加滿攪拌冷卻杯身", "倒入威士忌攪拌", "緩緩注入蘇打水"]
            },
            {
                id: 17,
                name: "White Lady (白色佳人)",
                base: "Gin",
                abvLevel: "med",
                abvDisplay: "22%",
                taste: "清爽/氣泡",
                ingredients: "琴酒, 橙酒, 檸檬汁",
                story: "純白色的優雅禮服。酸度銳利，像極了一位高冷的美人。她不會討好你，但你會忍不住想靠近，品嚐那份冰冷的純粹。",
                img: "https://www.1shot.tw/wp-content/uploads/2019/06/640px-White_Lady_Cocktail.jpg",
                method: "搖盪 (Shake)",
                glass: "淺碟香檳杯 (Coupe)",
                steps: ["材料加冰搖盪均勻", "濾冰倒入冰凍酒杯", "擠壓檸檬皮噴油"]
            },
            {
                id: 18,
                name: "Godfather (教父)",
                base: "Whiskey",
                abvLevel: "high",
                abvDisplay: "35%",
                taste: "酸甜/果香",
                ingredients: "蘇格蘭威士忌, 杏仁香甜酒",
                story: "只有兩種材料，卻構建出一個權力的世界。杏仁的甜味包裹著威士忌的煙燻，像極了那個男人——溫柔，但致命。",
                img: "https://www.liquor.com/thmb/0m6ieTCcAnzSVaHaaIL2v7c_BkY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/godfather-1200x628-email-3ac17589333c4c34b4900c780e343118.jpg",
                method: "直調 (Build)",
                glass: "傳統杯 (Rocks)",
                steps: ["杯中放入大冰塊", "倒入威士忌與杏仁酒", "輕輕攪拌混合"]
            },
            {
                id: 19,
                name: "Cuba Libre (自由古巴)",
                base: "Rum",
                abvLevel: "med",
                abvDisplay: "12%",
                taste: "酸甜/果香",
                ingredients: "蘭姆酒, 可樂, 檸檬角",
                story: "別叫它蘭姆可樂，這是對自由的渴望。在那段動盪的歲月裡，這杯酒代表了無數人的吶喊。現在，它只是快樂的代名詞。",
                img: "https://punchdrink.com/wp-content/uploads/2014/07/Cuba-Libre.jpg?w=1000",
                method: "直調 (Build)",
                glass: "高球杯 (Highball)",
                steps: ["擠壓檸檬角丟入杯中", "加冰倒入蘭姆酒", "補滿可樂攪拌"]
            },
            {
                id: 20,
                name: "Matador (鬥牛士)",
                base: "Tequila",
                abvLevel: "med",
                abvDisplay: "20%",
                taste: "清爽/氣泡",
                ingredients: "龍舌蘭, 鳳梨汁, 檸檬汁",
                story: "不像瑪格麗特那麼有名，但更有個性。鳳梨的酸甜中和了龍舌蘭的狂野。這是一場舌尖上的競技，你，準備好面對公牛了嗎？",
                img: "https://cuervo.com/wp-content/uploads/2023/08/cuervo-cocktail-recipe-matador-hero-mobile.jpeg",
                method: "搖盪 (Shake)",
                glass: "淺碟香檳杯 (Coupe)",
                steps: ["所有材料加入雪克杯", "加冰用力搖盪", "濾冰倒入杯中"]
            },
            {
                id: 22,
                name: "Pink Lady (粉紅佳人)",
                base: "Gin",
                abvLevel: "med",
                abvDisplay: "18%",
                taste: "酸甜/果香",
                ingredients: "琴酒, 蛋白, 紅石榴糖漿, 檸檬汁",
                story: "像是穿著絲綢禮服的名媛，外表甜美粉嫩，內在卻是琴酒的剛烈。這是一杯有反差感的酒，溫柔地讓你卸下防備。",
                img: "https://punchdrink.com/wp-content/uploads/2022/01/Article-Pink-Lady-Cocktail-Recipe-Gage-and-Tollner-NYC.jpg?w=800",
                method: "搖盪 (Shake)",
                glass: "淺碟香檳杯 (Coupe)",
                steps: ["先不加冰進行乾搖(Dry Shake)", "加入冰塊再次搖盪", "雙重過濾出綿密泡沫"]
            },
            {
                id: 23,
                name: "Sex on the Beach (性感的海灘)",
                base: "Vodka",
                abvLevel: "med",
                abvDisplay: "13%",
                taste: "酸甜/果香",
                ingredients: "伏特加, 水蜜桃酒, 蔓越莓汁, 柳橙汁",
                story: "名字讓人臉紅心跳，喝起來卻是純純的夏日戀情。滿滿的熱帶果香，閉上眼，彷彿能聽見海浪拍打沙灘的聲音。",
                img: "https://hips.hearstapps.com/hmg-prod/images/sex-on-the-beach-secondary-6442f7c409343.jpg?crop=1xw:1xh;center,top&resize=980:*",
                method: "搖盪 (Shake)",
                glass: "颶風杯 (Hurricane)",
                steps: ["所有材料加冰搖盪", "倒入裝滿冰塊的杯中", "放上柳橙切片裝飾"]
            },
            {
                id: 24,
                name: "Piña Colada (鳳梨可樂達)",
                base: "Rum",
                abvLevel: "low",
                abvDisplay: "11%",
                taste: "酸甜/果香",
                ingredients: "蘭姆酒, 椰漿, 鳳梨汁",
                story: "『如果你喜歡在雨中漫步...』這是一首關於逃離與私奔的歌。濃郁的椰奶香氣，是通往假期模式的單程車票。",
                img: "https://barbits.co.uk/cdn/shop/articles/how-to-make-a-classic-pina-colada-tropical-creamy-refreshing-2181301.png?v=1762192111",
                method: "攪拌/搖盪 (Blend/Shake)",
                glass: "颶風杯 (Hurricane)",
                steps: ["材料加入雪克杯用力搖盪", "或與冰塊放入果汁機打", "倒入杯中鳳梨裝飾"]
            },
            {
                id: 25,
                name: "Mint Julep (薄荷朱利普)",
                base: "Whiskey",
                abvLevel: "high",
                abvDisplay: "27%",
                taste: "清爽/氣泡",
                ingredients: "波本威士忌, 新鮮薄荷, 砂糖, 碎冰",
                story: "美國南方的熱情待客之道。大量的碎冰與薄荷，將威士忌的火辣鎮壓得服服貼貼。在炎熱的日子裡，它是唯一的救贖。",
                img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cv-x4fb8wEMzvpoZNKbT4mg-s62akY7Lag&s",
                method: "直調 (Build)",
                glass: "金屬杯 (Julep Cup)",
                steps: ["杯底輕壓薄荷與糖", "加滿碎冰倒入威士忌", "攪拌至杯壁結霜"]
            },
            {
                id: 26,
                name: "Tequila Slammer (龍舌蘭衝撞)",
                base: "Tequila",
                abvLevel: "med",
                abvDisplay: "20%",
                taste: "清爽/氣泡",
                ingredients: "龍舌蘭, 雪碧 (或氣泡酒)",
                story: "這不是品酒，這是儀式。蓋住杯口，用力敲擊桌面，趁著氣泡瘋狂湧出時一口飲盡。這是一杯用來打破沈默與尷尬的派對開關。",
                img: "https://www.thebottleclub.com/cdn/shop/articles/TBC_recipe_image_70-608437.jpg?v=1707229809",
                method: "直調 (Build)",
                glass: "一口杯 (Shot)",
                steps: ["龍舌蘭與雪碧1:1倒入", "蓋住杯口用力敲擊桌面", "趁氣泡湧出時飲盡"]
            },
            {
                id: 27,
                name: "Tom Collins (湯姆柯林斯)",
                base: "Gin",
                abvLevel: "low",
                abvDisplay: "10%",
                taste: "清爽/氣泡",
                ingredients: "琴酒, 檸檬汁, 糖漿, 蘇打水",
                story: "琴酒界的檸檬汽水，簡單卻極度耐喝。就像那位總是穿著白襯衫、乾淨俐落的老朋友，無論什麼時候見面，都讓人感到舒服。",
                img: "https://www.thebottleclub.com/cdn/shop/articles/TBC_recipe_image_16-967231.jpg?v=1707230597",
                method: "搖盪 (Shake)",
                glass: "高球杯 (Highball)",
                steps: ["基酒與酸甜加冰搖盪", "濾入裝滿冰塊的杯中", "補滿蘇打水稍微攪拌"]
            },
            {
                id: 28,
                name: "Black Russian (黑色俄羅斯)",
                base: "Vodka",
                abvLevel: "high",
                abvDisplay: "33%",
                taste: "苦甜/大人味",
                ingredients: "伏特加, 咖啡利口酒",
                story: "比白俄羅斯更純粹，更冷酷。沒有鮮奶的修飾，只有酒精與咖啡的直球對決。適合在深夜，不需要任何安慰的時候喝。",
                img: "https://ik.imagekit.io/vjt1kualr/drinks/black_russian/main-image.jpg",
                method: "直調 (Build)",
                glass: "傳統杯 (Rocks)",
                steps: ["杯中加入大冰塊", "倒入伏特加與咖啡酒", "輕輕攪拌冷卻"]
            },
            {
                id: 29,
                name: "Zombie (殭屍)",
                base: "Rum",
                abvLevel: "high",
                abvDisplay: "35%+",
                taste: "酸甜/果香",
                ingredients: "黑/白/金蘭姆酒 (混三種), 鳳梨汁, 百香果糖漿",
                story: "Tiki 文化的傳奇。因為酒精濃度太高，傳說喝完兩杯就會像殭屍一樣行屍走肉。它甜美得讓你失去戒心，然後給你致命一擊。",
                img: "https://d3u2gohddm28e7.cloudfront.net/wp-content/uploads/2023/08/Zombie%E8%AA%BF%E9%85%92.jpg",
                method: "搖盪 (Shake)",
                glass: "Tiki杯/高球杯",
                steps: ["所有蘭姆酒與果汁搖盪", "濾入裝滿碎冰的杯中", "加上豐富的熱帶裝飾"]
            },
            {
                id: 30,
                name: "Rusty Nail (銹釘)",
                base: "Whiskey",
                abvLevel: "high",
                abvDisplay: "33%",
                taste: "苦甜/大人味",
                ingredients: "蘇格蘭威士忌, 蜂蜜威士忌利口酒 (Drambuie)",
                story: "一杯屬於硬漢的酒，辛納屈 (Frank Sinatra) 的最愛。名字聽起來粗獷，口感卻帶著蜂蜜的草本香。是經歷過歲月洗禮後的沈穩味道。",
                img: "https://www.liquor.com/thmb/8eQKWH8ttWJgA8v_DhvKT38LWXU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/rusty-nail-4000x4000-primary-ig-989c6683bf8b41a78351896b79d6d01c.jpg",
                method: "直調 (Build)",
                glass: "傳統杯 (Rocks)",
                steps: ["杯中加入冰塊", "倒入蘇格蘭威士忌", "加入蜂蜜酒攪拌"]
            },
            {
                id: 31,
                name: "El Diablo (惡魔)",
                base: "Tequila",
                abvLevel: "med",
                abvDisplay: "13%",
                taste: "酸甜/果香",
                ingredients: "龍舌蘭, 黑醋栗利口酒, 薑汁啤酒, 檸檬",
                story: "紅色的外表下，藏著薑汁的辛辣與龍舌蘭的野性。它像是一個迷人的壞主意，你知道不該碰，但就是無法抗拒。",
                img: "https://i0.wp.com/cocktail4party.com/wp-content/uploads/2022/05/IMG_2385-e1652880888992-951x1024.jpg?resize=475%2C507&ssl=1",
                method: "直調 (Build)",
                glass: "高球杯 (Highball)",
                steps: ["杯中加冰倒入龍舌蘭", "加入檸檬汁與黑醋栗酒", "補滿薑汁啤酒"]
            },
            {
                id: 32,
                name: "Moscow Mule (莫斯科騾子)",
                base: "Vodka",
                abvLevel: "low",
                abvDisplay: "11%",
                taste: "清爽/氣泡",
                ingredients: "伏特加, 薑汁啤酒, 檸檬角",
                story: "這是一場行銷的勝利，也是一頭倔強的騾子。銅杯是為了保冷，更是為了讓你覺得這杯酒「值得」這個價錢。薑味的辛辣踹醒了伏特加的無聊，適合那些想喝點酒，但又不想承認自己在喝酒的人。",
                img: "https://www.thebottleclub.com/cdn/shop/articles/TBC_recipe_image_10-845540.jpg?v=1707230657",
                method: "直調 (Build)",
                glass: "銅馬克杯 (Copper Mug)",
                steps: ["杯中擠入檸檬角並投入", "加入冰塊與伏特加", "補滿薑汁啤酒攪拌"]
            },
            {
                id: 33,
                name: "Vodka Martini (伏特加馬丁尼)",
                base: "Vodka",
                abvLevel: "high",
                abvDisplay: "35%",
                taste: "辛辣/不甜",
                ingredients: "伏特加, 不甜香艾酒, 檸檬皮",
                story: "007 的固執，也是極簡主義的極致（或者是缺乏想像力）。沒有琴酒杜松子的干擾，它純粹得像是一塊液態的冰。這杯酒不適合尋找安慰，它適合那些需要絕對冷靜、或者單純想快速進入狀況的功利主義者。",
                img: "https://www.allrecipes.com/thmb/bU0nAuF70D9fY__AaVVHr5Pfjuw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/221893-vodka-martini-cocktail-DDMFS-4x3-1b2e90f80aae4627beaca1e0aec38af4.jpg",
                method: "攪拌/搖盪 (Stir/Shake)",
                glass: "馬丁尼杯 (Martini)",
                steps: ["材料加冰攪拌至冷卻", "濾冰倒入冰凍酒杯", "噴附檸檬皮油"]
            },
            {
                id: 34,
                name: "Whiskey Sour (威士忌酸酒)",
                base: "Whiskey",
                abvLevel: "med",
                abvDisplay: "16%",
                taste: "酸甜/果香",
                ingredients: "波本威士忌, 檸檬汁, 糖漿, 蛋白, 苦精",
                story: "原本粗獷的威士忌，被迫穿上了蛋白霜的蓬蓬裙。口感如絲綢般滑順，是大眾對烈酒的妥協。這是一杯安全的酒，適合那些想裝作懂威士忌，但其實怕辣的入門者。",
                img: "https://d3u2gohddm28e7.cloudfront.net/wp-content/uploads/2019/01/Social-Whiskey-Sour-3-1.jpg",
                method: "搖盪 (Shake)",
                glass: "傳統杯 (Rocks)",
                steps: ["不加冰乾搖打發蛋白", "加冰再次用力搖盪", "濾冰倒入杯中滴上苦精"]
            },
            {
                id: 35,
                name: "Jungle Bird (叢林鳥)",
                base: "Rum",
                abvLevel: "med",
                abvDisplay: "18%",
                taste: "苦甜/大人味",
                ingredients: "黑蘭姆酒, 金巴利 (Campari), 鳳梨汁, 檸檬汁, 糖漿",
                story: "誰說熱帶調酒只能傻甜？金巴利的苦味像是一隻闖入樂園的猛禽，瞬間撕裂了鳳梨的甜膩。這杯酒獻給那些在海島度假時，依然無法完全放鬆、習慣自找苦吃的都市靈魂。",
                img: "https://www.liquor.com/thmb/QjIyRSNkJhajy4FJOWMmae7vQ-M=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/jungle-bird-720x720-primary-549e0765f87e412488cf864e012e2e25.jpg",
                method: "搖盪 (Shake)",
                glass: "傳統杯 (Rocks)",
                steps: ["所有材料加冰用力搖盪", "連同冰塊倒入杯中", "鳳梨葉裝飾"]
            },
            {
                id: 36,
                name: "Oaxaca Old Fashioned (瓦哈卡老派)",
                base: "Tequila",
                abvLevel: "high",
                abvDisplay: "32%",
                taste: "辛辣/不甜",
                ingredients: "陳年龍舌蘭, 梅茲卡爾 (Mezcal), 龍舌蘭糖漿, 苦精",
                story: "如果你以為龍舌蘭只能做派對爛酒，這杯酒會狠狠打你的臉。煙燻、泥土、歲月的味道。這是墨西哥荒漠的營火，乾燥、濃烈。喝這杯酒的人，通常不喜歡說話，也不喜歡聽廢話。",
                img: "https://www.azuniatequila.com/wp-content/uploads/2020/08/iStock-661980450-scaled.jpg",
                method: "攪拌 (Stir)",
                glass: "經典杯 (Old Fashioned)",
                steps: ["糖漿與苦精攪拌均勻", "加入基酒與大冰塊", "攪拌冷卻噴燒烤橙皮"]
            },
            {
                id: 37,
                name: "French 75 (法式75)",
                base: "Gin",
                abvLevel: "high",
                abvDisplay: "28%",
                taste: "清爽/氣泡",
                ingredients: "琴酒, 香檳 (氣泡酒), 檸檬汁, 糖漿",
                story: "優雅的氣泡上升，喝起來像是慶祝勝利的香檳，但琴酒的後勁會像砲彈一樣擊中你。這是披著羊皮的狼，美麗，但絕對致命。適合那些外表光鮮亮麗，內心卻渴望毀滅的時刻。",
                img: "https://hips.hearstapps.com/hmg-prod/images/french-75-index-65de3a4e51fe7.jpeg?crop=0.565xw:1.00xh;0.358xw,0&resize=1200:*",
                method: "搖盪 (Shake)",
                glass: "香檳杯 (Flute)",
                steps: ["琴酒檸檬糖漿搖盪冷卻", "濾入香檳杯中", "補滿冰鎮香檳"]
            },
            {
                id: 38,
                name: "Paloma (帕洛瑪)",
                base: "Tequila",
                abvLevel: "low",
                abvDisplay: "12%",
                taste: "清爽/氣泡",
                ingredients: "龍舌蘭, 葡萄柚蘇打, 萊姆汁, 鹽口",
                story: "比起瑪格麗特，這才是墨西哥人真正喝的東西。簡單、廉價、有效。它不假裝高深，就是為了在炎熱的日子裡解渴。有的時候，平民美食比米其林更能撫慰人心。",
                img: "https://www.alcohol.com.tw/upload/news_life_m/ALL_news_life_21L06_tp6hkdta72.jpg",
                method: "直調 (Build)",
                glass: "高球杯 (Highball)",
                steps: ["杯口抹鹽加入冰塊", "倒入龍舌蘭與萊姆汁", "補滿葡萄柚蘇打攪拌"]
            },
            {
                id: 39,
                name: "Boulevardier (林蔭大道)",
                base: "Whiskey",
                abvLevel: "high",
                abvDisplay: "30%",
                taste: "苦甜/大人味",
                ingredients: "威士忌, 金巴利 (Campari), 甜香艾酒",
                story: "基本上就是換了威士忌底的 Negroni。如果說 Negroni 是義大利的優雅花花公子，Boulevardier 就是美國的世故銀行家。更厚重、更溫暖，也更難看透。",
                img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0K9f63ZA3O_pRuIc0-b1gvmmyWwl0Liaaow&s",
                method: "攪拌 (Stir)",
                glass: "傳統杯 (Rocks)",
                steps: ["所有材料加冰攪拌", "濾冰倒入裝冰新杯", "噴灑橙皮油"]
            },
            {
                id: 40,
                name: "Dark 'n' Stormy (月黑風高)",
                base: "Rum",
                abvLevel: "low",
                abvDisplay: "13%",
                taste: "清爽/氣泡",
                ingredients: "黑蘭姆酒, 薑汁啤酒, 檸檬角",
                story: "名字聽起來很文藝，其實就是懶人調酒。薑汁的刺激與黑蘭姆酒的焦糖味碰撞，像是一場發生在海上的短暫風暴。適合那些想要冒險感，但實際上只想坐在沙發上的人。",
                img: "https://www.alcohol.com.tw/upload/news_life_m/ALL_news_life_21L06_vnwyc42chz.jpg",
                method: "直調 (Build)",
                glass: "高球杯 (Highball)",
                steps: ["杯中加冰倒入薑汁啤酒", "緩緩倒入黑蘭姆酒分層", "以檸檬角裝飾"]
            },
            {
                id: 41,
                name: "Espresso Martini (濃縮咖啡馬丁尼)",
                base: "Vodka",
                abvLevel: "high",
                abvDisplay: "25%",
                taste: "苦甜/大人味",
                ingredients: "伏特加, 濃縮咖啡, 咖啡利口酒, 糖漿",
                story: "派對尾聲的救命稻草。咖啡因與酒精的矛盾擁抱，讓你清醒地做著錯誤的決定。你喝它不是因為喜歡咖啡，而是因為你不想承認今晚已經結束了。",
                img: "https://dosmaderas.com/wp-content/uploads/2021/10/Dos-Maderas-rum-Cocktail-Espresso-Martini-HERO-6.jpg",
                method: "搖盪 (Shake)",
                glass: "馬丁尼杯 (Martini)",
                steps: ["熱咖啡加糖融化", "加冰與酒大力搖盪出泡", "雙重過濾放上咖啡豆"]
            },
            {
                id: 42,
                name: "Gimlet (琴蕾)",
                base: "Gin",
                abvLevel: "med",
                abvDisplay: "24%",
                taste: "酸甜/果香",
                ingredients: "琴酒, 萊姆汁, 糖漿",
                story: "銳利、直接。它像是海明威小說裡的對話，沒有多餘的形容詞。這不是一杯用來細細品味的酒，這是一杯用來把事情講清楚的酒。酸度會讓你的腦袋稍微清醒一點。",
                img: "https://www.liquor.com/thmb/mi0oeRqiuSED3lwQOOWgjZY493s=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Gimlet-1500x1500-hero-7af9450103b9437d8d5b7206a6ddfe43.jpg",
                method: "搖盪 (Shake)",
                glass: "淺碟香檳杯 (Coupe)",
                steps: ["材料加冰搖盪均勻", "濾冰倒入冰凍酒杯", "以萊姆輪裝飾"]
            },
            {
                id: 43,
                name: "Bloody Mary (血腥瑪麗)",
                base: "Vodka",
                abvLevel: "med",
                abvDisplay: "14%",
                taste: "苦甜/大人味",
                ingredients: "伏特加, 番茄汁, 檸檬, 辣醬, 芹菜",
                story: "偽裝成沙拉的雞尾酒。它是社會大眾唯一允許你在早上十點飲用的酒精。它並不真的解宿醉，只是延後痛苦的到來，但我們都心甘情願地相信這個謊言。",
                img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_wUCOodfun3R_GbmyVZkocZiDAz8kmPe9xg&s",
                method: "滾動 (Roll)",
                glass: "高球杯 (Highball)",
                steps: ["杯中加冰與調味料", "來回倒入另一杯混和", "放入芹菜棒裝飾"]
            },
            {
                id: 44,
                name: "Penicillin (盤尼西林)",
                base: "Whiskey",
                abvLevel: "med",
                abvDisplay: "22%",
                taste: "酸甜/果香",
                ingredients: "調和威士忌, 泥煤威士忌, 薑糖漿, 檸檬, 蜂蜜",
                story: "現代經典。用煙燻味治癒靈魂的藥。薑的辛辣與泥煤的消毒水味，喝起來像是在蘇格蘭高地的寒風中生了一堆火。這不是給小朋友喝的果汁。",
                img: "https://upload.wikimedia.org/wikipedia/commons/1/18/The_Spotted_Owl_-_Penicillin.jpg",
                method: "搖盪 (Shake)",
                glass: "傳統杯 (Rocks)",
                steps: ["除泥煤酒外搖盪", "倒入加冰的杯中", "最後漂浮泥煤威士忌"]
            },
            {
                id: 45,
                name: "El Presidente (總統)",
                base: "Rum",
                abvLevel: "high",
                abvDisplay: "28%",
                taste: "辛辣/不甜",
                ingredients: "陳年蘭姆酒, 不甜香艾酒, 橙酒, 紅石榴糖漿",
                story: "在 Mojito 變紅之前，這才是古巴上流社會的選擇。它乾淨、複雜，帶著政治家的圓滑與世故。喝這杯酒需要一點年紀，或者至少，一點對舊時代的嚮往。",
                img: "https://images.vocus.cc/55c794d1-a4e9-4224-be60-48d862278bdb.jpg",
                method: "攪拌 (Stir)",
                glass: "淺碟香檳杯 (Coupe)",
                steps: ["所有材料加冰攪拌", "濾冰倒入冰凍酒杯", "噴附橙皮油"]
            },
            {
                id: 46,
                name: "Vesper (薇絲朋)",
                base: "Gin",
                abvLevel: "high",
                abvDisplay: "35%",
                taste: "辛辣/不甜",
                ingredients: "琴酒, 伏特加, 麗葉酒 (Lillet Blanc)",
                story: "龐德女郎的名字，也是一杯容易被低估的重砲。琴酒與伏特加的混血，消除了彼此的缺點，只留下酒精的純粹衝擊。喝完它，記得確認你的心跳還在不在。",
                img: "https://image-cdn-flare.qdm.cloud/q69c866e2b26c9/image/data/31.%E7%B6%93%E5%85%B8%E8%AA%BF%E9%85%92/48dd9c040d7ed9944e1707a8126f0b40.jpg",
                method: "搖盪 (Shake)",
                glass: "馬丁尼杯 (Martini)",
                steps: ["所有材料加冰用力搖盪", "濾冰倒入香檳杯或馬丁尼杯", "削一大片檸檬皮裝飾"]
            },
            {
                id: 47,
                name: "Caipiroska (凱匹羅斯卡)",
                base: "Vodka",
                abvLevel: "med",
                abvDisplay: "15%",
                taste: "酸甜/果香",
                ingredients: "伏特加, 萊姆角, 砂糖",
                story: "巴西國酒 Caipirinha 的伏特加版本。去掉了甘蔗酒的草本野味，只留下萊姆的暴力酸甜。這是一杯沒有靈魂但極度好喝的派對飲料，適合不想思考只需狂歡的夜晚。",
                img: "https://barschool.b-cdn.net/wp-content/uploads/2023/01/EBS-caipiroska-recipe.jpg",
                method: "搗壓 (Muddle)",
                glass: "傳統杯 (Rocks)",
                steps: ["杯中搗碎萊姆與糖", "加入碎冰與伏特加", "攪拌均勻至杯壁結霜"]
            },
            {
                id: 48,
                name: "White Russian (白俄羅斯)",
                base: "Vodka",
                abvLevel: "low",
                abvDisplay: "16%",
                taste: "苦甜/大人味",
                ingredients: "伏特加, 咖啡利口酒, 鮮奶油",
                story: "電影《謀殺綠腳趾》讓它起死回生。說穿了就是酒精版的巧克力牛奶，成人的液體甜點。喝它是為了逃避現實，享受那種高熱量的罪惡感。別談什麼層次了，好喝、會胖，就這樣。",
                img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRn09QoH93v2VgVV2H7P41Ca9jwLKhZ-ApS4w&s",
                method: "直調 (Build)",
                glass: "傳統杯 (Rocks)",
                steps: ["冰塊裝滿杯子", "倒入伏特加與咖啡酒攪拌", "緩緩淋上鮮奶油做分層"]
            },
            {
                id: 49,
                name: "Sazerac (薩澤拉克)",
                base: "Whiskey",
                abvLevel: "high",
                abvDisplay: "30%",
                taste: "辛辣/不甜",
                ingredients: "裸麥威士忌, 苦艾酒 (Absinthe), 裴喬氏苦精, 方糖",
                story: "紐奧良的官方雞尾酒，也是雞尾酒的老祖宗。苦艾酒的刷杯（Rinse）是關鍵，那股藥草味不是每個人都受得了。這不是派對酒，這是給那些歷經風霜、只想安靜喝杯烈酒的老靈魂。",
                img: "https://www.liquor.com/thmb/Ob_GjDCNJE0a8rHE7YfUK8txAmg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/sazerac-1500x1500-hero-62326d995cdb4a79a6a0a3bd4a98cef9.jpg",
                method: "攪拌 (Stir)",
                glass: "傳統杯 (Rocks)",
                steps: ["冰杯並用苦艾酒涮過倒掉", "威士忌與糖苦精加冰攪拌", "濾入杯中噴檸檬皮油"]
            },
            {
                id: 50,
                name: "Singapore Sling (新加坡司令)",
                base: "Gin",
                abvLevel: "med",
                abvDisplay: "17%",
                taste: "酸甜/果香",
                ingredients: "琴酒, 櫻桃白蘭地, 鳳梨汁, 檸檬汁, 紅石榴糖漿, 苦精, 蘇打水",
                story: "原本是為了讓殖民地女性能公開飲酒而設計的「果汁」。現在多半淪為觀光客的昂貴糖水。成分複雜到很少有酒吧能調對味道，通常你喝到的只是紅色的人工色素味。",
                img: "https://cdn.twistandtoast.com/uploads/2023/10/A-singapore-sling-recipe-Feature_3-scaled-1.jpg",
                method: "搖盪 (Shake)",
                glass: "颶風杯 (Hurricane)",
                steps: ["除蘇打水外材料搖盪", "濾入裝冰高球杯", "補少許蘇打水"]
            },
            {
                id: 51,
                name: "Hemingway Daiquiri (海明威戴吉利)",
                base: "Rum",
                abvLevel: "high",
                abvDisplay: "22%",
                taste: "酸甜/果香",
                ingredients: "白蘭姆酒, 葡萄柚汁, 瑪拉斯奇諾櫻桃酒, 檸檬汁",
                story: "海明威有糖尿病，所以這杯酒不加糖，並加倍了蘭姆酒。口感極乾（Dry）、偏酸，帶有葡萄柚的苦味。這不是給螞蟻人喝的，是給那些想在酒精中尋找靈感（或毀滅）的作家喝的。",
                img: "https://mixology.com.tw/images/recipe/pic/R008.jpg",
                method: "搖盪 (Shake)",
                glass: "淺碟香檳杯 (Coupe)",
                steps: ["所有材料加冰用力搖盪", "雙重過濾倒入冰杯", "以檸檬輪裝飾"]
            },
            {
                id: 52,
                name: "Aviation (飛行)",
                base: "Gin",
                abvLevel: "high",
                abvDisplay: "27%",
                taste: "酸甜/果香",
                ingredients: "琴酒, 紫羅蘭利口酒, 瑪拉斯奇諾櫻桃酒, 檸檬汁",
                story: "夢幻的淡紫色，喝起來卻像在吃肥皂（對某些人來說）。紫羅蘭的花香極難駕馭，多一分太妖豔，少一分太無聊。這是一杯視覺大於味覺的網美始祖。",
                img: "https://www.alcohol.com.tw/upload/news_life_m/ALL_news_life_21L03_dzpp7nb4aj.jpg",
                method: "搖盪 (Shake)",
                glass: "淺碟香檳杯 (Coupe)",
                steps: ["所有材料加冰搖盪", "濾入冰凍的酒杯", "放入一顆酒漬櫻桃"]
            },
            {
                id: 53,
                name: "Kamikaze (神風特攻隊)",
                base: "Vodka",
                abvLevel: "high",
                abvDisplay: "25%",
                taste: "酸甜/果香",
                ingredients: "伏特加, 橙酒, 檸檬汁",
                story: "這通常以 Shot 的形式出現。名字取得很壯烈，其實就是廉價的買醉捷徑。酸甜好入口，讓你一杯接一杯，直到你像神風特攻隊一樣，頭痛欲裂地墜毀在隔天早晨。",
                img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPSjx5qCvekIYAMgsOaowjzqK-UggDu-WWSw&s",
                method: "搖盪 (Shake)",
                glass: "一口杯 (Shot) 或 淺碟杯",
                steps: ["材料1:1:1加冰搖盪", "濾掉冰塊倒入杯中", "一口飲盡"]
            },
            {
                id: 54,
                name: "New York Sour (紐約酸酒)",
                base: "Whiskey",
                abvLevel: "med",
                abvDisplay: "16%",
                taste: "酸甜/果香",
                ingredients: "波本威士忌, 檸檬汁, 糖漿, 紅酒",
                story: "威士忌酸酒的升級版，漂浮的紅酒層像是一抹血色夕陽。單寧的澀味中和了酸甜，增加了口感的複雜度。這是一杯長得好看，喝起來也有點料的實力派。",
                img: "https://images.vocus.cc/70bb03eb-f07b-48da-ba34-9ebd211ed416.jpg",
                method: "搖盪 (Shake)",
                glass: "傳統杯 (Rocks)",
                steps: ["除紅酒外材料搖盪", "濾入裝滿冰塊的杯中", "使用湯匙背面緩緩引流紅酒漂浮"]
            },
            {
                id: 55,
                name: "Tommy's Margarita (湯米瑪格麗特)",
                base: "Tequila",
                abvLevel: "high",
                abvDisplay: "22%",
                taste: "酸甜/果香",
                ingredients: "龍舌蘭, 萊姆汁, 龍舌蘭糖漿",
                story: "現代調酒師更推崇的版本。拿掉了橙酒的干擾，只保留龍舌蘭的純粹與糖漿的蜜香。如果你想知道龍舌蘭真正的味道，點這個，別點那種加了色素糖漿的冰沙。",
                img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCuzxMzwH-iH5iSN7ltG0LhBZTd0cCG74jBQ&s",
                method: "搖盪 (Shake)",
                glass: "傳統杯 (Rocks)",
                steps: ["所有材料加冰搖盪", "倒入裝滿冰塊的杯中", "不需鹽口，可加萊姆角"]
            },
            {
                id: 56,
                name: "Sea Breeze (海風)",
                base: "Vodka",
                abvLevel: "low",
                abvDisplay: "10%",
                taste: "酸甜/果香",
                ingredients: "伏特加, 蔓越莓汁, 葡萄柚汁",
                story: "80年代的流行，清爽、粉紅、無害。它喝起來就像早餐的果汁，非常適合在海邊假裝自己很健康。酒精感極低，是入門者的安全牌。",
                img: "https://mixthatdrink.com/wp-content/uploads/2009/06/sea-breeze-cocktail-750x1126.jpg",
                method: "直調 (Build)",
                glass: "高球杯 (Highball)",
                steps: ["杯中裝滿冰塊", "倒入伏特加", "依序倒入兩種果汁攪拌"]
            },
            {
                id: 57,
                name: "Bramble (黑莓)",
                base: "Gin",
                abvLevel: "med",
                abvDisplay: "18%",
                taste: "酸甜/果香",
                ingredients: "琴酒, 檸檬汁, 糖漿, 黑莓利口酒 (Crème de Mûre)",
                story: "倫敦誕生的現代經典。碎冰與黑莓酒的渲染，像極了黑莓果醬流淌在雪地上。別被它可愛的外表騙了，琴酒的基底還是很紮實的。喝完記得檢查牙齒有沒有變黑。",
                img: "https://upload.wikimedia.org/wikipedia/commons/2/22/Bramble_Cocktail1.jpg",
                method: "直調 (Build)",
                glass: "傳統杯 (Rocks)",
                steps: ["琴酒檸檬糖漿搖盪倒入裝碎冰杯", "頂層淋上黑莓酒", "黑莓與檸檬裝飾"]
            },
            {
                id: 58,
                name: "Irish Coffee (愛爾蘭咖啡)",
                base: "Whiskey",
                abvLevel: "low",
                abvDisplay: "12%",
                taste: "苦甜/大人味",
                ingredients: "愛爾蘭威士忌, 熱咖啡, 紅糖, 鮮奶油",
                story: "機場酒吧的傳奇。威士忌讓身體暖和，咖啡讓你保持清醒（理論上）。完美的愛爾蘭咖啡，鮮奶油必須冰涼且漂浮，透過冷奶油喝到熱咖啡，那種冷熱交替才是精髓。",
                img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMhTVB48vozO-Q5O7ykNoiSDisSi-muknVuQ&s",
                method: "直調 (Build)",
                glass: "耐熱咖啡杯 (Mug)",
                steps: ["熱咖啡溶化紅糖", "加入威士忌攪拌", "背面湯匙緩衝鋪上打發鮮奶油"]
            },
            {
                id: 59,
                name: "Corpse Reviver No.2 (死而復生二號)",
                base: "Gin",
                abvLevel: "high",
                abvDisplay: "26%",
                taste: "酸甜/果香",
                ingredients: "琴酒, 麗葉酒, 橙酒, 檸檬汁, 苦艾酒",
                story: "號稱能把死人（宿醉者）救活的解酒酒。「早上十一點前喝一杯精神百倍，連喝四杯就會死回去。」味道複雜平衡，帶有淡淡的茴香暗示，是內行人才懂點的酒。",
                img: "https://www.liquor.com/thmb/63abwr0MwkXxI0MbGBqqS7Vlmdo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Corpse_Reviver_No_2_Credit_Tim_Nusog_3000x3000_primary-4ea0fd7311ef4ad9b919a4c6ec7d75cc.jpg",
                method: "搖盪 (Shake)",
                glass: "淺碟香檳杯 (Coupe)",
                steps: ["苦艾酒涮杯後倒掉", "其餘材料搖盪均勻", "濾入杯中"]
            },
            {
                id: 60,
                name: "The Last Word (最後一語)",
                base: "Gin",
                abvLevel: "high",
                abvDisplay: "28%",
                taste: "酸甜/果香",
                ingredients: "琴酒, 綠夏翠絲 (Green Chartreuse), 瑪拉斯奇諾櫻桃酒, 萊姆汁",
                story: "禁酒令時期的遺珠。綠夏翠絲的草藥味極強，這是一杯在口腔中爆炸的炸彈。酸、甜、草本、酒精完美平衡。喝完這杯，你通常真的說不出話來了，只能點頭讚嘆。",
                img: "https://ik.imagekit.io/vjt1kualr/drinks/last_word/main-image.jpg",
                method: "搖盪 (Shake)",
                glass: "淺碟香檳杯 (Coupe)",
                steps: ["四種材料等比例加入搖盪", "濾入冰凍酒杯", "投入一顆酒漬櫻桃"]
            },
            {
                id: 61,
                name: "Gibson (吉普森)",
                base: "Gin",
                abvLevel: "high",
                abvDisplay: "35%",
                taste: "辛辣/不甜",
                ingredients: "琴酒, 不甜香艾酒, 珍珠洋蔥",
                story: "基本上就是把馬丁尼的橄欖換成珍珠洋蔥。但這顆洋蔥改變了一切，帶來了一種詭異但迷人的鹹鮮味（Umami）。這是給那些嫌馬丁尼還不夠怪的人喝的。",
                img: "https://www.thespruceeats.com/thmb/gAu9I-KDnWqumNQ7QiZgNT1elKw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/_gibson-cocktail-recipe-759669-hero-5bca0f2dc9e77c0051c6c83e.jpg",
                method: "攪拌 (Stir)",
                glass: "馬丁尼杯 (Martini)",
                steps: ["琴酒與香艾酒攪拌冷卻", "濾入冰凍酒杯", "放入珍珠洋蔥裝飾"]
            },
            {
                id: 62,
                name: "Harvey Wallbanger (哈維撞牆)",
                base: "Vodka",
                abvLevel: "med",
                abvDisplay: "15%",
                taste: "酸甜/果香",
                ingredients: "伏特加, 柳橙汁, 加利安奴 (Galliano)",
                story: "螺絲起子多加了一層黃色的義大利香草酒。傳說是一個叫哈維的衝浪客喝醉後撞牆而得名（聽聽就好）。重點是那個長得像棒球棒的酒瓶，和那股像感冒糖漿的香草味。",
                img: "https://www.thespruceeats.com/thmb/0SFGEX0vC9nQd1m_d7XSAd_GyHI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/harvey-wallbanger-recipe-759308-hero-01-03b0f2ff672c4a89b6700b6404aa4c56.jpg",
                method: "直調 (Build)",
                glass: "高球杯 (Highball)",
                steps: ["伏特加與柳橙汁加冰攪拌", "最後緩緩漂浮加利安奴酒", "柳橙片裝飾"]
            },
            {
                id: 63,
                name: "Batanga (巴坦加)",
                base: "Tequila",
                abvLevel: "low",
                abvDisplay: "12%",
                taste: "酸甜/果香",
                ingredients: "龍舌蘭, 可樂, 萊姆汁, 鹽口",
                story: "墨西哥版的自由古巴。關鍵在於要用「切萊姆的刀」來攪拌（這是儀式感）。鹽口與可樂的搭配意外地合拍，鹹甜氣泡中帶著龍舌蘭的野性。簡單粗暴，但是好喝。",
                img: "https://cuervo.com/wp-content/uploads/2023/08/cuervo-cocktail-recipe-batanga.jpeg",
                method: "直調 (Build)",
                glass: "高球杯 (Highball)",
                steps: ["杯口抹鹽加入冰塊", "擠入萊姆汁投入萊姆角", "倒入酒與可樂用刀子攪拌"]
            },
            {
                id: 64,
                name: "Negroni Sbagliato (錯誤內格羅尼)",
                base: "Gin",
                abvLevel: "low",
                abvDisplay: "9%",
                taste: "苦甜/大人味",
                ingredients: "琴酒(少許), 金巴利, 甜香艾酒, 氣泡酒",
                story: "這是一個美麗的錯誤。調酒師本想拿琴酒，卻誤拿了氣泡酒。它保留了內格羅尼的苦澀靈魂，卻變得像汽水一樣輕盈。適合那些想裝成熟，但體力已經不支的夜晚。",
                img: "https://www.einfachkochen.de/sites/einfachkochen.de/files/styles/full_width_tablet_4_3/public/2023-03/negroni_sbagliato_6116.jpg?h=4521fff0&itok=08tF4n54",
                method: "直調 (Build)",
                glass: "傳統杯 (Rocks)",
                steps: ["杯中加冰依序倒入材料", "輕輕攪拌", "放上橙片裝飾"]
            },
            {
                id: 65,
                name: "Gin Rickey (琴瑞奇)",
                base: "Gin",
                abvLevel: "low",
                abvDisplay: "8%",
                taste: "辛辣/不甜",
                ingredients: "琴酒, 萊姆汁, 蘇打水",
                story: "它是琴通寧的「極簡版」，去掉了通寧水的糖分。喝起來乾澀、銳利、充滿氣泡。這是給那些連通寧水的甜味都覺得是負擔、活得極度硬派的人喝的。",
                img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKbnjXEe3ybH_eFIRgvqaKcLIYF_yjv1eMkw&s",
                method: "直調 (Build)",
                glass: "高球杯 (Highball)",
                steps: ["杯中擠入萊姆汁並投入", "加入琴酒與冰塊", "補滿蘇打水"]
            },
            {
                id: 66,
                name: "Bijou (碧珠)",
                base: "Gin",
                abvLevel: "med",
                abvDisplay: "24%",
                taste: "苦甜/大人味",
                ingredients: "琴酒, 綠夏翠絲, 甜香艾酒, 橙味苦精",
                story: "法語意為「珠寶」。琴酒是鑽石，香艾酒是紅寶石，夏翠絲是綠寶石。這是一杯充滿藥草味、濃郁且苦甜平衡的重磅調酒。適合那些對人生層次感有強迫症的挑剔鬼。",
                img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStXFeTrLDcr5xOjhuZZH5PESY8T0XW8Er30w&s",
                method: "攪拌 (Stir)",
                glass: "馬丁尼杯 (Martini)",
                steps: ["所有材料加冰攪拌至極冷", "濾冰倒入杯中", "擠壓橙皮裝飾"]
            },
            {
                id: 67,
                name: "Right Hand (右手)",
                base: "Rum",
                abvLevel: "high",
                abvDisplay: "28%",
                taste: "苦甜/大人味",
                ingredients: "陳年蘭姆酒, 金巴利, 甜香艾酒, 巧克力苦精",
                story: "內格羅尼的蘭姆酒變奏版。巧克力苦精帶出了蘭姆酒的菸草與焦糖感。它比 Negroni 更深沉，像是一位在古巴港口抽雪茄的老紳士，低調但充滿力量。",
                img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAPIgbYmj4Y-FvkhC8yDUpf2HEOdHfFUgeEg&s",
                method: "攪拌 (Stir)",
                glass: "傳統杯 (Rocks)",
                steps: ["所有材料加冰攪拌", "濾入冰塊杯中", "噴灑橙皮油"]
            },
            {
                id: 68,
                name: "Le Grand Fizz (伏特加接骨木花蘇打)",
                base: "Vodka",
                abvLevel: "high",
                abvDisplay: "26%",
                taste: "清爽/氣泡",
                ingredients: "伏特加, 接骨木花利口酒, 萊姆汁, 蘇打水",
                story: "伏特加也能優雅得像香檳。接骨木花的清香掩蓋了高濃度酒精的刺鼻，氣泡感十足。這是一杯適合在高檔泳池派對上，邊看帥哥美女邊喝的偽裝飲料。",
                img: "https://www.sidechef.com/recipe/0a98bbaa-80a7-4152-a210-bdfea13fd790.jpg?d=1408x1120",
                method: "直調 (Build)",
                glass: "紅酒杯 (Wine Glass)",
                steps: ["杯中裝滿大冰塊", "依序倒入伏特加、利口酒與酸甜", "補滿蘇打水並攪拌"]
            },
            {
                id: 69,
                name: "Rosita (羅莎莉塔)",
                base: "Tequila",
                abvLevel: "low",
                abvDisplay: "12%",
                taste: "苦甜/大人味",
                ingredients: "龍舌蘭, 甜香艾酒, 不甜香艾酒, 金巴利",
                story: "龍舌蘭版的低酒精 Negroni。同時使用兩種香艾酒來平衡龍舌蘭的土味與金巴利的苦味。它有一種複雜的草本香氣，適合那些在夏日午後，想安靜獨處的靈魂。",
                img: "https://www.trensse.com/wp-content/uploads/2023/08/Rosita.jpg",
                method: "攪拌 (Stir)",
                glass: "傳統杯 (Rocks)",
                steps: ["所有材料加冰攪拌", "濾冰倒入冰杯", "放上檸檬皮裝飾"]
            },
            {
                id: 70,
                name: "Mexican Mule (墨西哥騾子)",
                base: "Tequila",
                abvLevel: "high",
                abvDisplay: "28%",
                taste: "清爽/氣泡",
                ingredients: "龍舌蘭(加倍), 薑汁啤酒, 萊姆汁",
                story: "把原本莫斯科騾子的伏特加換成龍舌蘭，並大幅提升濃度。薑的辛辣與龍舌蘭的植物感完美結合，這一腳踹下去會讓你頭暈目眩。這不是為了清爽，這是為了挑戰極限。",
                img: "https://foodieandwine.com/wp-content/uploads/2022/03/Mexican_Mules_5.jpg",
                method: "直調 (Build)",
                glass: "銅杯或高球杯",
                steps: ["杯中加入大量冰塊", "倒入高劑量龍舌蘭與萊姆汁", "補滿薑汁啤酒"]
            }
    // ...
];

// 這行最重要，讓別的檔案可以讀到這份資料庫
module.exports = cocktails;